/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package capaPresentacion;

/**
 *
 * @author shivi
 */
public class FormProveedor extends javax.swing.JPanel {

    /**
     * Creates new form FormProveedor
     */
    public FormProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   private void limpiarTextos() {
        txtRazonSPrv.setText("");
        txtRucPrv.setText("");
        txtDireccionPrv.setText("");
        txtLugarPrv.setText("");
        txtEmailPrv.setText("");
     
      //  activarControles();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmailPrv = new javax.swing.JFormattedTextField();
        txtLugarPrv = new javax.swing.JTextField();
        txtRazonSPrv = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDireccionPrv = new javax.swing.JTextField();
        comboTipoPrv = new javax.swing.JComboBox();
        botonBuscarPrv = new javax.swing.JButton();
        botonAgregarPrv = new javax.swing.JButton();
        btnSalirPrv = new javax.swing.JButton();
        botonMostrarPrv = new javax.swing.JButton();
        botonNuevoProv = new javax.swing.JButton();
        botonEliminarPrv = new javax.swing.JButton();
        botonEditarPrv = new javax.swing.JButton();
        botonCancelarPrv = new javax.swing.JButton();
        txtRucPrv = new javax.swing.JFormattedTextField();
        txtTelefonoPrv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Razon Social:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("Email:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel1.setText("Ruc:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setText("Lugar:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setText("Direccion:");

        txtEmailPrv.setEditable(false);

        txtLugarPrv.setEditable(false);

        txtRazonSPrv.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel8.setText("Tipo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Telefono:");

        txtDireccionPrv.setEditable(false);

        comboTipoPrv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Eliga Proveedor", "Distribuidores", "Fabricante", "Proveedor Directos e Indirectos", "Proveedor Local", " " }));
        comboTipoPrv.setEnabled(false);
        comboTipoPrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoPrvActionPerformed(evt);
            }
        });

        botonBuscarPrv.setText("Buscar Proveedor");
        botonBuscarPrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPrvActionPerformed(evt);
            }
        });

        botonAgregarPrv.setFont(new java.awt.Font("Tahoma", 0, 12));
        botonAgregarPrv.setText("Agregar");
        botonAgregarPrv.setEnabled(false);
        botonAgregarPrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarPrvActionPerformed(evt);
            }
        });

        btnSalirPrv.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnSalirPrv.setText("Salir");
        btnSalirPrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirPrvActionPerformed(evt);
            }
        });

        botonMostrarPrv.setFont(new java.awt.Font("Tahoma", 0, 12));
        botonMostrarPrv.setText("Mostar");
        botonMostrarPrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarPrvActionPerformed(evt);
            }
        });

        botonNuevoProv.setFont(new java.awt.Font("Tahoma", 0, 12));
        botonNuevoProv.setText("nuevo");
        botonNuevoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoProvActionPerformed(evt);
            }
        });

        botonEliminarPrv.setFont(new java.awt.Font("Tahoma", 0, 12));
        botonEliminarPrv.setText("Eliminar");
        botonEliminarPrv.setEnabled(false);
        botonEliminarPrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarPrvActionPerformed(evt);
            }
        });

        botonEditarPrv.setFont(new java.awt.Font("Tahoma", 0, 12));
        botonEditarPrv.setText("Editar");
        botonEditarPrv.setEnabled(false);
        botonEditarPrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarPrvActionPerformed(evt);
            }
        });

        botonCancelarPrv.setFont(new java.awt.Font("Tahoma", 0, 12));
        botonCancelarPrv.setText("Cancelar");
        botonCancelarPrv.setEnabled(false);
        botonCancelarPrv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarPrvActionPerformed(evt);
            }
        });

        txtRucPrv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###########"))));

        txtTelefonoPrv.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccionPrv, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtLugarPrv, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEmailPrv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(2, 2, 2))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtRucPrv, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonBuscarPrv)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addComponent(txtRazonSPrv))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(comboTipoPrv, 0, 116, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefonoPrv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnSalirPrv, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(botonNuevoProv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAgregarPrv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEditarPrv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarPrv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMostrarPrv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCancelarPrv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRucPrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarPrv))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRazonSPrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailPrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLugarPrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonoPrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDireccionPrv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoPrv, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCancelarPrv, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(botonEliminarPrv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEditarPrv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAgregarPrv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonNuevoProv, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(botonMostrarPrv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalirPrv, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 1, 24));
        jLabel10.setText("MANTENIMIENTO DE PROVEEDOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void activarControles() {
        txtRucPrv.setEditable(true);
        botonCancelarPrv.setEnabled(false);
        botonEliminarPrv.setEnabled(false);
        botonNuevoProv.setEnabled(true);
        botonMostrarPrv.setEnabled(true);
        botonBuscarPrv.setEnabled(true);
        botonAgregarPrv.setEnabled(false);
        botonEditarPrv.setEnabled(false);
    }
    
     private void activarTextos(boolean b) {
        txtRazonSPrv.setEditable(b);
        txtRucPrv.setEditable(b);
        txtDireccionPrv.setEditable(b);
        txtLugarPrv.setEnabled(b);
        txtEmailPrv.setEnabled(b);
    
    }
    
    private void comboTipoPrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoPrvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoPrvActionPerformed

    private void botonBuscarPrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPrvActionPerformed
        // TODO add your handling code here:
//        if (txtRucPrv.getText().compareTo("") != 0) {
//            int result = JOptionPane.showConfirmDialog(
//                    this, "Deseas Buscar al Proveedor para Modificarlo?",
//                    "Mensaje..!!",
//                    JOptionPane.YES_NO_OPTION);
//
//            if (result == JOptionPane.YES_OPTION) {
//                buscarProveedor();
//                botonNuevoProv.setEnabled(false);
//                botonMostrarPrv.setEnabled(false);
//                botonCancelarPrv.setEnabled(true);
//                botonEditarPrv.setEnabled(true);
//                activarTextos(true);
//                txtRucPrv.setEditable(false);
//            }
//            if (result == JOptionPane.NO_OPTION) {
//                buscarProveedor();
//                botonEliminarPrv.setEnabled(true);
//                botonNuevoProv.setEnabled(false);
//                botonCancelarPrv.setEnabled(true);
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "Ingrese DNI que Desea Buscar");
//        }
    }//GEN-LAST:event_botonBuscarPrvActionPerformed

    private void botonAgregarPrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarPrvActionPerformed
        // TODO add your handling code here:
//        if (txtRucPrv.getText().compareTo("") != 0 && txtRazonSPrv.getText().compareTo("") != 0 && txtEmailPrv.getText().compareTo("") != 0
//                && txtCelularPrv.getText().compareTo("") != 0 && txtLugarPrv.getText().compareTo("") != 0 && txtTelefonoPrv.getText().compareTo("") != 0
//                && txtDireccionPrv.getText().compareTo("") != 0) {
//            Proveedor p = new Proveedor() {
//            };
//            p.setRuc(txtRucPrv.getText());
//            p.setRazonSocial(txtRazonSPrv.getText());
//            p.setEmail(txtEmailPrv.getText());
//            p.setCelular(txtCelularPrv.getText());
//            p.setLugar(txtLugarPrv.getText());
//            p.setTelefono(txtTelefonoPrv.getText());
//            p.setDireccion(txtDireccionPrv.getText());
//            p.setTipo((String) comboTipoPrv.getSelectedItem());
//            try {
//                BDProveedor.insertarProveedor(p);
//            } catch (SQLException e) {
//                JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
//            }
//            JOptionPane.showMessageDialog(null, "[ Datos Agregados ]");
//
//        } else {
//            JOptionPane.showMessageDialog(null, "Llene todo los Campos");
//        }
    }//GEN-LAST:event_botonAgregarPrvActionPerformed

    private void btnSalirPrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirPrvActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSalirPrvActionPerformed

    private void botonMostrarPrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarPrvActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_botonMostrarPrvActionPerformed

    private void botonNuevoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoProvActionPerformed
       
        limpiarTextos();
        activarTextos(true);
        botonAgregarPrv.setEnabled(true);
        botonNuevoProv.setEnabled(false);
        botonCancelarPrv.setEnabled(true);
        botonMostrarPrv.setEnabled(false);
        botonBuscarPrv.setEnabled(false);
        
    }//GEN-LAST:event_botonNuevoProvActionPerformed

    private void botonEliminarPrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarPrvActionPerformed
        // TODO add your handling code here:
//        try {
//            Proveedor p = BDProveedor.buscarProveedor(txtRucPrv.getText());
//            if (p == null) {
//                JOptionPane.showMessageDialog(null, "No existe");
//            } else {
//                BDProveedor.eliminarProveedor(p.getRuc());
//                JOptionPane.showMessageDialog(null, "Se Elimino Exitosamente..OKz!!");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
//        }
//        limpiarTextos();
    }//GEN-LAST:event_botonEliminarPrvActionPerformed

    private void botonEditarPrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarPrvActionPerformed
        // TODO add your handling code here:
//        Proveedor p;
//        try {
//            p = BDProveedor.buscarProveedor(txtRucPrv.getText());
//            p.setRazonSocial(txtRazonSPrv.getText());
//            p.setEmail(txtEmailPrv.getText());
//            p.setCelular(txtCelularPrv.getText());
//            p.setLugar(txtLugarPrv.getText());
//            p.setTelefono(txtTelefonoPrv.getText());
//            p.setDireccion(txtDireccionPrv.getText());
//            p.setTipo((String) comboTipoPrv.getSelectedItem());
//            BDProveedor.actualizarProveedor(p);
//            JOptionPane.showMessageDialog(null, " [ Datos Actualizados ]");
//        } catch (SQLException e) {
//            JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
//        }
//        limpiarTextos();
    }//GEN-LAST:event_botonEditarPrvActionPerformed

    private void botonCancelarPrvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarPrvActionPerformed
        // TODO add your handling code here:
//        limpiarTextos();
//        activarTextos(false);
//        txtRucPrv.setEditable(true);
//        botonCancelarPrv.setEnabled(false);
//        botonEliminarPrv.setEnabled(false);
//        botonNuevoProv.setEnabled(true);
//        botonMostrarPrv.setEnabled(true);
//        btnBuscarPrv.setEnabled(true);
//        botonAgregarPrv.setEnabled(false);
//        botonEditarPrv.setEnabled(false);
    }//GEN-LAST:event_botonCancelarPrvActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarPrv;
    private javax.swing.JButton botonBuscarPrv;
    private javax.swing.JButton botonCancelarPrv;
    private javax.swing.JButton botonEditarPrv;
    private javax.swing.JButton botonEliminarPrv;
    private javax.swing.JButton botonMostrarPrv;
    private javax.swing.JButton botonNuevoProv;
    private javax.swing.JButton btnSalirPrv;
    private javax.swing.JComboBox comboTipoPrv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDireccionPrv;
    private javax.swing.JFormattedTextField txtEmailPrv;
    private javax.swing.JTextField txtLugarPrv;
    private javax.swing.JTextField txtRazonSPrv;
    private javax.swing.JFormattedTextField txtRucPrv;
    private javax.swing.JTextField txtTelefonoPrv;
    // End of variables declaration//GEN-END:variables
}
